### ISSUE TITLE
sorting of codes

### ISSUE THREAD

**Issue by PawelSpoon** [a-dekker/ClubCode#2]
do you see a chance.either to sort the list alphabetically or let the user define the order?

currently the.order is based on creation

**Comment by a-dekker** [comment]
I'll have a look at an alphabetical sort.

**Comment by PawelSpoon** [comment]
great thanks !
if you use sql to store the data an order by would be the easiest.
else i have a piece of code stolen from somewhere that does the sorting of a list:

    function sortModel()
    {
        print("sorting")
        for(var i=0; i<upcomingModel.count; i++)
        {
            for(var j=0; j<i; j++)
            {
                if(upcomingModel.get(i).date === upcomingModel.get(j).date)
                   upcomingModel.move(i,j,1)
                //break
            }
        }
    }

**Comment by a-dekker** [comment]
There is no sql database used. Another option would be to sort on the C++ side. But QML may be the easiest. I'll see if I can use this.

**Comment by a-dekker** [comment]
Both options do not seem to be that straightforward unfortunately.

**Comment by PawelSpoon** [comment]
thanks for trying !

**Comment by PawelSpoon** [comment]
hello,
today i have tried this:
i have modified this function in MainViewModel.cpp as follows:
it sorts, add and remove does work. newly added ones will still pop up at the end, but after restart they are sorted.

void MainViewModel::load()
{
    QFile file("/home/nemo/.local/share/harbour-clubcode/database");

    if (file.open(QIODevice::ReadOnly))
    {
        QDataStream stream(&file);

        while (!stream.atEnd())
        {
            CodeViewModel* item = new CodeViewModel();
            stream >> *item;

            m_codes << item;
        }
        for(int i=0; i< m_codes.count(); i++)
        {
            for(int j=0; j<i; j++)
            {
                if (m_codes.at(i)->property("name") <= m_codes.at(j)->property("name"))
                {
                    m_codes.move(i,j);
                }
            }
        }
     }
}

**Comment by a-dekker** [comment]
I did some std::sort sorting over there, but that did not work out.
Thanks for assisting, will try it myself soon!

**Comment by a-dekker** [comment]
Closed by https://github.com/a-dekker/ClubCode/commit/04ef10872ff0a948db825917335e480919b1f80c

**Comment by PawelSpoon** [comment]
great ! on the qml side i did also fail
did not write any c++ code since 15 years and also my qml skills are very limited ;)
and thanks to the very simple IDE i needed like 3 hrs to get the 4 lines working :-)
